### ISSUE TITLE
资源文件

### ISSUE THREAD

**Issue by high726** [mrqatom/ChangeResourceDemo#1]
请问一个关于资源文件的问题 我运行了你的demo 要求替换与被替换的资源文件是同一个名字 如果我想用gradle对资源文件重命名 请问有没有好思路呢

**Comment by mrqatom** [comment]
按我的思路直接copy你的文件进去就好了，如果要改变java文件中的引用名就比较麻烦了，要更改所有引用到该资源文件的地方

**Comment by high726** [comment]
更改所有引用到该资源文件的地方 这个在gradle里面有相应的task吗

**Comment by mrqatom** [comment]
就我所知，没有...这种只能自己写，推荐使用android的manifestplaceholders放到manifest里，然后java引用。或者buildConfigField也可以，具体用法可自行谷歌

**Comment by high726** [comment]
好的 谢谢
