### ISSUE TITLE
桌面图标没有修改过来

### ISSUE THREAD

**Issue by victorfan336** [mrqatom/ChangeResourceDemo#2]
我下载了demo，运行起来，每个apk包的applicationIds和appNames都修改过来了，但是桌面图标没有修改过来，我也解压apk看了下，确实没有修改过来。

**Comment by mrqatom** [comment]
你有修改任何代码吗？或者操作是否正确，按文档来执行的吗？路径必须保证对应。执行gradle命令时有没有打印“${variantFlavorName} resource is changed!”的log

**Comment by victorfan336** [comment]
@mrqatom 你好， 是有打印的哦， 所有生成的apk都有打印，但是图标都是默认的那个图标

**Comment by mrqatom** [comment]
你打包之后资源目录的文件也没有改变吗？提供一下打包时的相应log资料

**Comment by jiusetian** [comment]
我遇到同样的情况，下面是build 的log
clean
:app:clean
:resourceflavors:clean
:app:preBuild UP-TO-DATE
:app:preDefine1DebugBuild
define1 resource is changed!
:app:compileDefine1DebugAidl
:app:compileDefine1DebugRenderscript
:app:checkDefine1DebugManifest
:app:generateDefine1DebugBuildConfig
:app:prepareLintJar UP-TO-DATE
:app:mainApkListPersistenceDefine1Debug
:app:generateDefine1DebugResValues
:app:generateDefine1DebugResources
:app:mergeDefine1DebugResources
:app:createDefine1DebugCompatibleScreenManifests
:app:processDefine1DebugManifest
:app:splitsDiscoveryTaskDefine1Debug
:app:processDefine1DebugResources
:app:generateDefine1DebugSources
:app:javaPreCompileDefine1Debug
:app:compileDefine1DebugJavaWithJavac
:app:compileDefine1DebugNdk NO-SOURCE
:app:compileDefine1DebugSources
:app:mergeDefine1DebugShaders
:app:compileDefine1DebugShaders
:app:generateDefine1DebugAssets
:app:mergeDefine1DebugAssets
:app:transformClassesWithDexBuilderForDefine1Debug
:app:transformDexArchiveWithExternalLibsDexMergerForDefine1Debug
:app:transformDexArchiveWithDexMergerForDefine1Debug
:app:mergeDefine1DebugJniLibFolders
:app:transformNativeLibsWithMergeJniLibsForDefine1Debug
:app:transformNativeLibsWithStripDebugSymbolForDefine1Debug
:app:processDefine1DebugJavaRes NO-SOURCE
:app:transformResourcesWithMergeJavaResForDefine1Debug
:app:validateSigningDefine1Debug
:app:packageDefine1Debug
:app:assembleDefine1Debug

**Comment by mrqatom** [comment]
@victorfan336 @jiusetian 看了一下，因为flavors.gradle里的flavorNames和defindpic文件夹下的文件名写错了，所以只要把defindpic下的文件名改了就好了

**Comment by jiusetian** [comment]
谢谢！
